// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpsygikmgrtuqoljoufv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc3lnaWttZ3J0dXFvbGpvdWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjY1NTQsImV4cCI6MjA2NDIwMjU1NH0.ZcNRAFDz6ASflLlKc8ixs1mpkckPDW5YlL5AcaInBew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);